version: '3.6'

services:
  sintrop-testnet:
    container_name: SINTROP-TESTNET
    tty: true
    ports:
      - "8551:8551"
      - "8545:8545"
    build:
      context: .
      dockerfile: Dockerfile
    networks: 
      - app-tunnel
    volumes:
      - ./:/app
networks: 
  app-tunnel:
    driver: bridge
